//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedMultiBindInjector_MultiBindSpecification {

        internal GeneratedMultiBindInjector_MultiBindSpecification CreateNewFrame() {
            return this;
        }

        internal System.Collections.Generic.IReadOnlyList<Phx.Inject.Tests.Data.Model.ILeaf> Fac_IReadOnlyList_GetListLeaf1(
                Phx.Inject.Tests.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.MultiBindSpecification.GetListLeaf1();
        }

        internal System.Collections.Generic.IReadOnlyList<Phx.Inject.Tests.Data.Model.ILeaf> Fac_IReadOnlyList_GetListLeaf2(
                Phx.Inject.Tests.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.MultiBindSpecification.GetListLeaf2();
        }

        internal System.Collections.Generic.ISet<Phx.Inject.Tests.Data.Model.ILeaf> Fac_ISet_GetSetLeaf1(
                Phx.Inject.Tests.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.MultiBindSpecification.GetSetLeaf1();
        }

        internal System.Collections.Generic.ISet<Phx.Inject.Tests.Data.Model.ILeaf> Fac_ISet_GetSetLeaf2(
                Phx.Inject.Tests.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.MultiBindSpecification.GetSetLeaf2();
        }

        internal System.Collections.Generic.IReadOnlySet<Phx.Inject.Tests.Data.Model.ILeaf> Fac_IReadOnlySet_GetSetLeaf1ReadOnly(
                Phx.Inject.Tests.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.MultiBindSpecification.GetSetLeaf1ReadOnly();
        }

        internal System.Collections.Generic.IReadOnlySet<Phx.Inject.Tests.Data.Model.ILeaf> Fac_IReadOnlySet_GetSetLeaf2ReadOnly(
                Phx.Inject.Tests.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.MultiBindSpecification.GetSetLeaf2ReadOnly();
        }

        internal System.Collections.Generic.IReadOnlyDictionary<System.String,Phx.Inject.Tests.Data.Model.ILeaf> Fac_IReadOnlyDictionary_GetDictLeaf1(
                Phx.Inject.Tests.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.MultiBindSpecification.GetDictLeaf1();
        }

        internal System.Collections.Generic.IReadOnlyDictionary<System.String,Phx.Inject.Tests.Data.Model.ILeaf> Fac_IReadOnlyDictionary_GetDictLeaf2(
                Phx.Inject.Tests.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.MultiBindSpecification.GetDictLeaf2();
        }
    }
}
#nullable restore
