//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedInjectorProviderTestInjector : Phx.Inject.Tests.IInjectorProviderTestInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedInjectorProviderTestInjector_CommonTestValueSpecification GeneratedInjectorProviderTestInjector_CommonTestValueSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedInjectorProviderTestInjector_CommonTestValueSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedInjectorProviderTestInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedInjectorProviderTestInjector_CommonTestValueSpecification: new Phx.Inject.Tests.GeneratedInjectorProviderTestInjector_CommonTestValueSpecification());
        }

        public System.Int32 GetInt() {
            return specContainers.GeneratedInjectorProviderTestInjector_CommonTestValueSpecification.GetInt(specContainers);
        }

        public System.Int32 GetLabelAInt() {
            return specContainers.GeneratedInjectorProviderTestInjector_CommonTestValueSpecification.GetIntLabelA(specContainers);
        }

        public System.String GetlabelAString() {
            return specContainers.GeneratedInjectorProviderTestInjector_CommonTestValueSpecification.GetStringLabelA(specContainers);
        }
    }
}
#nullable restore
