//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.2.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedPropertyFactoryInjector : Phx.Inject.Tests.IPropertyFactoryInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedPropertyFactoryInjector_IPropertyFactorySpec GeneratedPropertyFactoryInjector_IPropertyFactorySpec,
                Phx.Inject.Tests.GeneratedPropertyFactoryInjector_PropertyFactoryStaticSpec GeneratedPropertyFactoryInjector_PropertyFactoryStaticSpec
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedPropertyFactoryInjector_IPropertyFactorySpec.CreateNewFrame(),
                        GeneratedPropertyFactoryInjector_PropertyFactoryStaticSpec.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedPropertyFactoryInjector(
                Phx.Inject.Tests.IPropertyFactorySpec iPropertyFactorySpec
        ) {
            specContainers = new SpecContainerCollection(
                    GeneratedPropertyFactoryInjector_IPropertyFactorySpec: new Phx.Inject.Tests.GeneratedPropertyFactoryInjector_IPropertyFactorySpec(iPropertyFactorySpec),
                    GeneratedPropertyFactoryInjector_PropertyFactoryStaticSpec: new Phx.Inject.Tests.GeneratedPropertyFactoryInjector_PropertyFactoryStaticSpec());
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetLeaf() {
            return specContainers.GeneratedPropertyFactoryInjector_IPropertyFactorySpec.PropFac_ILeaf_Leaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.StringLeaf GetStringLeaf() {
            return specContainers.GeneratedPropertyFactoryInjector_PropertyFactoryStaticSpec.PropFac_StringLeaf_StringLeaf(specContainers);
        }
    }
}
#nullable restore
