//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedContainerInjector_ContainerSpecification {
        private GeneratedContainerInjector_ContainerSpecification? parent;
        private System.Int32? int32;
        private Phx.Inject.Tests.Data.Model.StringLeaf? _stringLeaf;
        private Phx.Inject.Tests.Data.Model.StringLeaf? stringLeaf {
            get { return _stringLeaf; }
            set {
                this._stringLeaf = value;
                if (parent != null) {
                    parent.stringLeaf = value;
                }
            }
        }

        internal GeneratedContainerInjector_ContainerSpecification CreateNewFrame() {
            var newFrame = new GeneratedContainerInjector_ContainerSpecification();
            newFrame.stringLeaf = this.stringLeaf;
            newFrame.parent = this;
            return newFrame;
        }

        internal System.Int32 Fac_Int32_GetInt(
                Phx.Inject.Tests.GeneratedContainerInjector.SpecContainerCollection specContainers
        ) {
            return int32 ??= Phx.Inject.Tests.ContainerSpecification.GetInt();
        }

        internal Phx.Inject.Tests.Data.Model.StringLeaf Fac_StringLeaf_GetStringLeaf(
                Phx.Inject.Tests.GeneratedContainerInjector.SpecContainerCollection specContainers
        ) {
            return stringLeaf ??= Phx.Inject.Tests.ContainerSpecification.GetStringLeaf(
                specContainers.GeneratedContainerInjector_ContainerSpecification.Fac_Int32_GetInt(specContainers));
        }

        internal System.Collections.Generic.IReadOnlyList<Phx.Inject.Tests.Data.Model.IntLeaf> Fac_IReadOnlyList_GetIntLeaf1(
                Phx.Inject.Tests.GeneratedContainerInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.ContainerSpecification.GetIntLeaf1(
                specContainers.GeneratedContainerInjector_GeneratedContainerInjector_ConstructorFactories.CtorFac_IntLeaf_IntLeaf(specContainers));
        }

        internal System.Collections.Generic.IReadOnlyList<Phx.Inject.Tests.Data.Model.IntLeaf> Fac_IReadOnlyList_GetIntLeaf2(
                Phx.Inject.Tests.GeneratedContainerInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.ContainerSpecification.GetIntLeaf2(
                specContainers.GeneratedContainerInjector_GeneratedContainerInjector_ConstructorFactories.CtorFac_IntLeaf_IntLeaf(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.Node Fac_Node_GetNode(
                Phx.Inject.Tests.GeneratedContainerInjector.SpecContainerCollection parentSpecContainer
        ) {
            var specContainers = parentSpecContainer.CreateNewFrame();
            return Phx.Inject.Tests.ContainerSpecification.GetNode(
                Phx.Inject.InjectionUtil.Combine<Phx.Inject.Tests.Data.Model.IntLeaf> (
                    specContainers.GeneratedContainerInjector_ContainerSpecification.Fac_IReadOnlyList_GetIntLeaf1(specContainers),
                    specContainers.GeneratedContainerInjector_ContainerSpecification.Fac_IReadOnlyList_GetIntLeaf2(specContainers)
                ));
        }

        internal Phx.Inject.Tests.Data.Model.Node Fac_WithScoped_Node_GetNode2(
                Phx.Inject.Tests.GeneratedContainerInjector.SpecContainerCollection parentSpecContainer
        ) {
            var specContainers = parentSpecContainer.CreateNewFrame();
            return Phx.Inject.Tests.ContainerSpecification.GetNode2(
                specContainers.GeneratedContainerInjector_GeneratedContainerInjector_ConstructorFactories.CtorFac_IntLeaf_IntLeaf(specContainers),
                specContainers.GeneratedContainerInjector_ContainerSpecification.Fac_StringLeaf_GetStringLeaf(specContainers));
        }
    }
}
#nullable restore
