//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class ConstructedChildInjector_NonConstructedSpecification {

        internal ConstructedChildInjector_NonConstructedSpecification CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf Fac_IntLeaf_GetIntLeaf(
                Phx.Inject.Tests.ConstructedChildInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.NonConstructedSpecification.GetIntLeaf(
                specContainers.ConstructedChildInjector_IConstructedSpecification.Fac_Int32_GetIntValue(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.OuterType Fac_OuterType_GetOuterType(
                Phx.Inject.Tests.ConstructedChildInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.NonConstructedSpecification.GetOuterType(
                specContainers.ConstructedChildInjector_ConstructedChildInjector_ConstructorFactories.CtorFac_AutoType_AutoType(specContainers),
                specContainers.ConstructedChildInjector_ConstructedChildInjector_ConstructorFactories.CtorFac_AutoTypeWithRequiredProperties_AutoTypeWithRequiredProperties(specContainers));
        }
    }
}
#nullable restore
