//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class ConstructedParentInjector_IConstructedChildExternalDependencies : Phx.Inject.Tests.IConstructedChildExternalDependencies {
        private readonly Phx.Inject.Tests.ConstructedParentInjector.SpecContainerCollection specContainers;

        public ConstructedParentInjector_IConstructedChildExternalDependencies(Phx.Inject.Tests.ConstructedParentInjector.SpecContainerCollection specContainers) {
            this.specContainers = specContainers;
        }

        public Phx.Inject.Tests.Data.Model.IntLeaf GetIntLeaf() {
            return specContainers.ConstructedParentInjector_NonConstructedSpecification.GetIntLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetILeaf() {
            return specContainers.ConstructedParentInjector_NonConstructedSpecification.GetIntLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.OuterType GetOuterType() {
            return specContainers.ConstructedParentInjector_NonConstructedSpecification.GetOuterType(specContainers);
        }
    }
}
#nullable restore
