//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.2.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedBuilderReferenceInjector_BuilderReferenceSpec {
        private Phx.Inject.Tests.Data.Model.IntLeaf? intLeaf;

        internal GeneratedBuilderReferenceInjector_BuilderReferenceSpec CreateNewFrame() {
            return this;
        }

        internal System.Int32 PropFac_Int32_IntValue(
                Phx.Inject.Tests.GeneratedBuilderReferenceInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.BuilderReferenceSpec.IntValue;
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf RefFac_IntLeaf_GetIntLeaf(
                Phx.Inject.Tests.GeneratedBuilderReferenceInjector.SpecContainerCollection specContainers
        ) {
            return intLeaf ??= Phx.Inject.Tests.BuilderReferenceSpec.GetIntLeaf(
                specContainers.GeneratedBuilderReferenceInjector_BuilderReferenceSpec.PropFac_Int32_IntValue(specContainers));
        }

        internal void RefBld_TestBuilderReferenceObject_BuildBuilderReferenceType(
                Phx.Inject.Tests.Data.Model.TestBuilderReferenceObject target,
                Phx.Inject.Tests.GeneratedBuilderReferenceInjector.SpecContainerCollection specContainers
        ) {
            Phx.Inject.Tests.BuilderReferenceSpec.BuildBuilderReferenceType(
                target,
                specContainers.GeneratedBuilderReferenceInjector_BuilderReferenceSpec.PropFac_Int32_IntValue(specContainers));
        }

        internal void RefBld_Field_TestBuilderReferenceObject_BuildBuilderReferenceTypeField(
                Phx.Inject.Tests.Data.Model.TestBuilderReferenceObject target,
                Phx.Inject.Tests.GeneratedBuilderReferenceInjector.SpecContainerCollection specContainers
        ) {
            Phx.Inject.Tests.BuilderReferenceSpec.BuildBuilderReferenceTypeField(
                target,
                specContainers.GeneratedBuilderReferenceInjector_BuilderReferenceSpec.PropFac_Int32_IntValue(specContainers));
        }
    }
}
#nullable restore
