//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class InjectorBuilderTestInjector : Phx.Inject.Tests.IInjectorBuilderTestInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.Data.InjectorBuilderTestInjector_CommonTestValueSpecification InjectorBuilderTestInjector_CommonTestValueSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        InjectorBuilderTestInjector_CommonTestValueSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public InjectorBuilderTestInjector() {
            specContainers = new SpecContainerCollection(
                    InjectorBuilderTestInjector_CommonTestValueSpecification: new Phx.Inject.Tests.Data.InjectorBuilderTestInjector_CommonTestValueSpecification());
        }

        public void BuildTestBuilder(Phx.Inject.Tests.Data.TestBuilderObject target) {
            specContainers.InjectorBuilderTestInjector_CommonTestValueSpecification.BuildTestBuilderObject(target, specContainers);
        }

        public void BuildTestBuilderLabelA(Phx.Inject.Tests.Data.TestBuilderObject target) {
            specContainers.InjectorBuilderTestInjector_CommonTestValueSpecification.BuildTestBuilderObjectLabelA(target, specContainers);
        }
    }
}
#nullable restore
