//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class ConstructedChildInjector_IConstructedChildExternalDependencies {
        private readonly Phx.Inject.Tests.IConstructedChildExternalDependencies instance;

        public ConstructedChildInjector_IConstructedChildExternalDependencies(Phx.Inject.Tests.IConstructedChildExternalDependencies instance) {
            this.instance = instance;
        }

        internal ConstructedChildInjector_IConstructedChildExternalDependencies CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf GetIntLeaf(
                Phx.Inject.Tests.ConstructedChildInjector.SpecContainerCollection specContainers
        ) {
            return instance.GetIntLeaf();
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf GetILeaf(
                Phx.Inject.Tests.ConstructedChildInjector.SpecContainerCollection specContainers
        ) {
            return instance.GetILeaf();
        }

        internal Phx.Inject.Tests.Data.Model.OuterType GetOuterType(
                Phx.Inject.Tests.ConstructedChildInjector.SpecContainerCollection specContainers
        ) {
            return instance.GetOuterType();
        }
    }
}
#nullable restore
