//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class CustomNamedInjector_CustomNamedInjector_ConstructorFactories {
        private Phx.Inject.Tests.Data.Model.AutoTypeWithFabricationMode? autoTypeWithFabricationMode;

        internal CustomNamedInjector_CustomNamedInjector_ConstructorFactories CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.AutoType CtorFac_AutoType_AutoType(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.AutoType(
                specContainers.CustomNamedInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers),
                specContainers.CustomNamedInjector_CustomNamedInjector_ConstructorFactories.CtorFac_AutoTypeWithFabricationMode_AutoTypeWithFabricationMode(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.AutoTypeWithRequiredProperties CtorFac_AutoTypeWithRequiredProperties_AutoTypeWithRequiredProperties(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.AutoTypeWithRequiredProperties(
                specContainers.CustomNamedInjector_CustomNamedInjector_ConstructorFactories.CtorFac_AutoType_AutoType(specContainers)
            ) {
                X = specContainers.CustomNamedInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers),
                Y = specContainers.CustomNamedInjector_CustomNamedInjector_ConstructorFactories.CtorFac_AutoTypeWithFabricationMode_AutoTypeWithFabricationMode(specContainers)
            };
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf CtorFac_IntLeaf_IntLeaf(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.IntLeaf(
                specContainers.CustomNamedInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.AutoTypeWithFabricationMode CtorFac_AutoTypeWithFabricationMode_AutoTypeWithFabricationMode(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return autoTypeWithFabricationMode ??= new Phx.Inject.Tests.Data.Model.AutoTypeWithFabricationMode(
                specContainers.CustomNamedInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers));
        }
    }
}
#nullable restore
