//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedBuilderReferenceInjector : Phx.Inject.Tests.IBuilderReferenceInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedBuilderReferenceInjector_BuilderReferenceSpec GeneratedBuilderReferenceInjector_BuilderReferenceSpec
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedBuilderReferenceInjector_BuilderReferenceSpec.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedBuilderReferenceInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedBuilderReferenceInjector_BuilderReferenceSpec: new Phx.Inject.Tests.GeneratedBuilderReferenceInjector_BuilderReferenceSpec());
        }

        public void Build(Phx.Inject.Tests.Data.Model.LazyType target) {
            specContainers.GeneratedBuilderReferenceInjector_BuilderReferenceSpec.GetReferenceBuildLazyType(target, specContainers);
        }

        public void BuildField(Phx.Inject.Tests.Data.Model.LazyType target) {
            specContainers.GeneratedBuilderReferenceInjector_BuilderReferenceSpec.GetReferenceBuildLazyTypeField(target, specContainers);
        }
    }
}
#nullable restore
