//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.2.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class BasicConstructedInjector_IConstructedSpecification {
        private readonly Phx.Inject.Tests.IConstructedSpecification instance;

        public BasicConstructedInjector_IConstructedSpecification(Phx.Inject.Tests.IConstructedSpecification instance) {
            this.instance = instance;
        }

        internal BasicConstructedInjector_IConstructedSpecification CreateNewFrame() {
            return this;
        }

        internal System.Int32 Fac_Int32_GetIntValue(
                Phx.Inject.Tests.BasicConstructedInjector.SpecContainerCollection specContainers
        ) {
            return instance.GetIntValue();
        }
    }
}
#nullable restore
