//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class ConstructedChildInjector : Phx.Inject.Tests.IConstructedChildInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.ConstructedChildInjector_IConstructedSpecification ConstructedChildInjector_IConstructedSpecification,
                Phx.Inject.Tests.ConstructedChildInjector_NonConstructedSpecification ConstructedChildInjector_NonConstructedSpecification,
                Phx.Inject.Tests.ConstructedChildInjector_ConstructedChildInjector_ConstructorFactories ConstructedChildInjector_ConstructedChildInjector_ConstructorFactories
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        ConstructedChildInjector_IConstructedSpecification.CreateNewFrame(),
                        ConstructedChildInjector_NonConstructedSpecification.CreateNewFrame(),
                        ConstructedChildInjector_ConstructedChildInjector_ConstructorFactories.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public ConstructedChildInjector(
                Phx.Inject.Tests.IConstructedSpecification iConstructedSpecification
        ) {
            specContainers = new SpecContainerCollection(
                    ConstructedChildInjector_IConstructedSpecification: new Phx.Inject.Tests.ConstructedChildInjector_IConstructedSpecification(iConstructedSpecification),
                    ConstructedChildInjector_NonConstructedSpecification: new Phx.Inject.Tests.ConstructedChildInjector_NonConstructedSpecification(),
                    ConstructedChildInjector_ConstructedChildInjector_ConstructorFactories: new Phx.Inject.Tests.ConstructedChildInjector_ConstructedChildInjector_ConstructorFactories());
        }

        public Phx.Inject.Tests.Data.Model.IntLeaf GetIntLeaf() {
            return specContainers.ConstructedChildInjector_NonConstructedSpecification.Fac_IntLeaf_GetIntLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetILeaf() {
            return specContainers.ConstructedChildInjector_NonConstructedSpecification.Fac_IntLeaf_GetIntLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.OuterType GetOuterType() {
            return specContainers.ConstructedChildInjector_NonConstructedSpecification.Fac_OuterType_GetOuterType(specContainers);
        }
    }
}
#nullable restore
