//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedPropertyFactoryInjector_IPropertyFactorySpec {
        private readonly Phx.Inject.Tests.IPropertyFactorySpec instance;

        public GeneratedPropertyFactoryInjector_IPropertyFactorySpec(Phx.Inject.Tests.IPropertyFactorySpec instance) {
            this.instance = instance;
        }

        internal GeneratedPropertyFactoryInjector_IPropertyFactorySpec CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf PropFac_ILeaf_Leaf(
                Phx.Inject.Tests.GeneratedPropertyFactoryInjector.SpecContainerCollection specContainers
        ) {
            return instance.Leaf;
        }
    }
}
#nullable restore
