//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class GeneratedNestedSpecInjector_OuterNestedSpecification_Inner {

        internal GeneratedNestedSpecInjector_OuterNestedSpecification_Inner CreateNewFrame() {
            var newFrame = new GeneratedNestedSpecInjector_OuterNestedSpecification_Inner();
            return newFrame;
        }

        internal System.Int32 GetIntValue(
                Phx.Inject.Tests.Data.Inject.GeneratedNestedSpecInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.OuterNestedSpecification.Inner.GetIntValue();
        }
    }
}
#nullable restore
