//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedQualifierTestInjector_QualifierSpecification {

        internal GeneratedQualifierTestInjector_QualifierSpecification CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf Fac_Phx_Inject_Tests_Data_Model_QualifierAAttribute_ILeaf_GetAttributeNamedLeafA(
                Phx.Inject.Tests.GeneratedQualifierTestInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.QualifierSpecification.GetAttributeNamedLeafA();
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf Fac_Phx_Inject_Tests_Data_Model_QualifierBAttribute_ILeaf_GetAttributeNamedLeafB(
                Phx.Inject.Tests.GeneratedQualifierTestInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.QualifierSpecification.GetAttributeNamedLeafB();
        }
    }
}
#nullable restore
