//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedParentInjector : Phx.Inject.Tests.IParentInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedParentInjector_ParentSpecification GeneratedParentInjector_ParentSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedParentInjector_ParentSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedParentInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedParentInjector_ParentSpecification: new Phx.Inject.Tests.GeneratedParentInjector_ParentSpecification());
        }

        public Phx.Inject.Tests.IChildInjector GetChildInjector() {
            return new Phx.Inject.Tests.GeneratedChildInjector(
                    iChildExternalDependencies: new Phx.Inject.Tests.GeneratedParentInjector_IChildExternalDependencies(specContainers));
        }
    }
}
#nullable restore
