//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedContainerInjector_GeneratedContainerInjector_ConstructorFactories {

        internal GeneratedContainerInjector_GeneratedContainerInjector_ConstructorFactories CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf GetConstructorintLeaf(
                Phx.Inject.Tests.GeneratedContainerInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.IntLeaf(
                specContainers.GeneratedContainerInjector_ContainerSpecification.GetInt(specContainers));
        }
    }
}
#nullable restore
