//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Inject {
    internal partial class GeneratedLabelInjector : Phx.Inject.Tests.Data.Inject.ILabelInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.Data.Specification.GeneratedLabelInjector_LabeledLeafSpecification GeneratedLabelInjector_LabeledLeafSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedLabelInjector_LabeledLeafSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedLabelInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedLabelInjector_LabeledLeafSpecification: new Phx.Inject.Tests.Data.Specification.GeneratedLabelInjector_LabeledLeafSpecification());
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetDefaultLeaf() {
            return specContainers.GeneratedLabelInjector_LabeledLeafSpecification.GetDefaultLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetNonDefaultLeafA() {
            return specContainers.GeneratedLabelInjector_LabeledLeafSpecification.GetNonDefaultLeafA(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetNonDefaultLeafB() {
            return specContainers.GeneratedLabelInjector_LabeledLeafSpecification.GetNonDefaultLeafB(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetAttributeNamedLeafA() {
            return specContainers.GeneratedLabelInjector_LabeledLeafSpecification.GetAttributeNamedLeafA(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetAttributeNamedLeafB() {
            return specContainers.GeneratedLabelInjector_LabeledLeafSpecification.GetAttributeNamedLeafB(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetStringNamedLeafA() {
            return specContainers.GeneratedLabelInjector_LabeledLeafSpecification.GetStringNamedLeafA(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.StringLeaf GetNamedStringLeaf() {
            return specContainers.GeneratedLabelInjector_LabeledLeafSpecification.GetNamedStringLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.Node GetNode() {
            return specContainers.GeneratedLabelInjector_LabeledLeafSpecification.GetNode(specContainers);
        }

        public void BuildLabeledLazyType(Phx.Inject.Tests.Data.Model.LazyType target) {
            specContainers.GeneratedLabelInjector_LabeledLeafSpecification.BuildLazyTypeLeafA(target, specContainers);
        }

        public void BuildUnlabeledLazyType(Phx.Inject.Tests.Data.Model.LazyType target) {
            specContainers.GeneratedLabelInjector_LabeledLeafSpecification.BuildLazyTypeDefault(target, specContainers);
        }
    }
}
#nullable restore
