//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class InjectorScopeTestInjector : Phx.Inject.Tests.IInjectorScopeTestInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.InjectorScopeTestInjector_InjectorScopeSpecification InjectorScopeTestInjector_InjectorScopeSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        InjectorScopeTestInjector_InjectorScopeSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public InjectorScopeTestInjector() {
            specContainers = new SpecContainerCollection(
                    InjectorScopeTestInjector_InjectorScopeSpecification: new Phx.Inject.Tests.InjectorScopeTestInjector_InjectorScopeSpecification());
        }

        public System.Int32 GetIntDefault() {
            return specContainers.InjectorScopeTestInjector_InjectorScopeSpecification.Fac_Int32_GetIntDefault(specContainers);
        }

        public System.Int32 GetIntRecurrent() {
            return specContainers.InjectorScopeTestInjector_InjectorScopeSpecification.Fac_Recurrent_Int32_GetIntRecurrent(specContainers);
        }

        public System.Int32 GetIntScoped() {
            return specContainers.InjectorScopeTestInjector_InjectorScopeSpecification.Fac_Scoped_Int32_GetIntScoped(specContainers);
        }
    }
}
#nullable restore
