//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedContainerInjector : Phx.Inject.Tests.IContainerInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedContainerInjector_ContainerSpecification GeneratedContainerInjector_ContainerSpecification,
                Phx.Inject.Tests.GeneratedContainerInjector_IContainerInjector_ConstructorFactories GeneratedContainerInjector_IContainerInjector_ConstructorFactories
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedContainerInjector_ContainerSpecification.CreateNewFrame(),
                        GeneratedContainerInjector_IContainerInjector_ConstructorFactories.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedContainerInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedContainerInjector_ContainerSpecification: new Phx.Inject.Tests.GeneratedContainerInjector_ContainerSpecification(),
                    GeneratedContainerInjector_IContainerInjector_ConstructorFactories: new Phx.Inject.Tests.GeneratedContainerInjector_IContainerInjector_ConstructorFactories());
        }

        public System.Collections.Generic.IReadOnlyList<Phx.Inject.Tests.Data.Model.IntLeaf> GetIntLeaves() {
            return Phx.Inject.InjectionUtil.Combine<Phx.Inject.Tests.Data.Model.IntLeaf>(
                specContainers.GeneratedContainerInjector_ContainerSpecification.Fac_IReadOnlyList_GetIntLeaf1(specContainers),
                specContainers.GeneratedContainerInjector_ContainerSpecification.Fac_IReadOnlyList_GetIntLeaf2(specContainers)
            );
        }

        public Phx.Inject.Tests.Data.Model.Node GetNode() {
            return specContainers.GeneratedContainerInjector_ContainerSpecification.Fac_Node_GetNode(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.Node GetNodeWithScoped() {
            return specContainers.GeneratedContainerInjector_ContainerSpecification.Fac_L_WithScoped_Node_GetNode2(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.StringLeaf GetStringLeaf() {
            return specContainers.GeneratedContainerInjector_ContainerSpecification.Fac_StringLeaf_GetStringLeaf(specContainers);
        }
    }
}
#nullable restore
