//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class GeneratedMultiBindInjector_MultiBindSpecification {

        internal GeneratedMultiBindInjector_MultiBindSpecification CreateNewFrame() {
            return this;
        }

        internal System.Collections.Generic.List<Phx.Inject.Tests.Data.Model.ILeaf> GetListLeaf1(
                Phx.Inject.Tests.Data.Inject.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.MultiBindSpecification.GetListLeaf1();
        }

        internal System.Collections.Generic.List<Phx.Inject.Tests.Data.Model.ILeaf> GetListLeaf2(
                Phx.Inject.Tests.Data.Inject.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.MultiBindSpecification.GetListLeaf2();
        }

        internal System.Collections.Generic.HashSet<Phx.Inject.Tests.Data.Model.ILeaf> GetSetLeaf1(
                Phx.Inject.Tests.Data.Inject.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.MultiBindSpecification.GetSetLeaf1();
        }

        internal System.Collections.Generic.HashSet<Phx.Inject.Tests.Data.Model.ILeaf> GetSetLeaf2(
                Phx.Inject.Tests.Data.Inject.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.MultiBindSpecification.GetSetLeaf2();
        }

        internal System.Collections.Generic.Dictionary<System.String,Phx.Inject.Tests.Data.Model.ILeaf> GetDictLeaf1(
                Phx.Inject.Tests.Data.Inject.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.MultiBindSpecification.GetDictLeaf1();
        }

        internal System.Collections.Generic.Dictionary<System.String,Phx.Inject.Tests.Data.Model.ILeaf> GetDictLeaf2(
                Phx.Inject.Tests.Data.Inject.GeneratedMultiBindInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.MultiBindSpecification.GetDictLeaf2();
        }
    }
}
#nullable restore
