//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedDefaultNamedInjector : Phx.Inject.Tests.IDefaultNamedInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.Data.GeneratedDefaultNamedInjector_CommonTestValueSpecification GeneratedDefaultNamedInjector_CommonTestValueSpecification,
                Phx.Inject.Tests.GeneratedDefaultNamedInjector_GeneratedDefaultNamedInjector_ConstructorFactories GeneratedDefaultNamedInjector_GeneratedDefaultNamedInjector_ConstructorFactories
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedDefaultNamedInjector_CommonTestValueSpecification.CreateNewFrame(),
                        GeneratedDefaultNamedInjector_GeneratedDefaultNamedInjector_ConstructorFactories.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedDefaultNamedInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedDefaultNamedInjector_CommonTestValueSpecification: new Phx.Inject.Tests.Data.GeneratedDefaultNamedInjector_CommonTestValueSpecification(),
                    GeneratedDefaultNamedInjector_GeneratedDefaultNamedInjector_ConstructorFactories: new Phx.Inject.Tests.GeneratedDefaultNamedInjector_GeneratedDefaultNamedInjector_ConstructorFactories());
        }

        public System.Int32 GetInt() {
            return specContainers.GeneratedDefaultNamedInjector_CommonTestValueSpecification.GetInt(specContainers);
        }
    }
}
#nullable restore
