//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class ConstructedParentInjector_ConstructedParentInjector_ConstructorFactories {
        private Phx.Inject.Tests.Data.Model.AutoTypeWithFabricationMode? autoTypeWithFabricationMode;

        internal ConstructedParentInjector_ConstructedParentInjector_ConstructorFactories CreateNewFrame() {
            return this;
        }

        internal System.Int32 GetConstructorint32(
                Phx.Inject.Tests.ConstructedParentInjector.SpecContainerCollection specContainers
        ) {
            return new System.Int32();
        }

        internal Phx.Inject.Tests.Data.Model.AutoType GetConstructorautoType(
                Phx.Inject.Tests.ConstructedParentInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.AutoType(
                specContainers.ConstructedParentInjector_NonConstructedSpecification.GetIntLeaf(specContainers),
                specContainers.ConstructedParentInjector_ConstructedParentInjector_ConstructorFactories.GetConstructorautoTypeWithFabricationMode(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.AutoTypeWithFabricationMode GetConstructorautoTypeWithFabricationMode(
                Phx.Inject.Tests.ConstructedParentInjector.SpecContainerCollection specContainers
        ) {
            return autoTypeWithFabricationMode ??= new Phx.Inject.Tests.Data.Model.AutoTypeWithFabricationMode();
        }
    }
}
#nullable restore
