//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class ConstructedChildInjector_IConstructedSpecification {
        private readonly Phx.Inject.Tests.IConstructedSpecification instance;

        public ConstructedChildInjector_IConstructedSpecification(Phx.Inject.Tests.IConstructedSpecification instance) {
            this.instance = instance;
        }

        internal ConstructedChildInjector_IConstructedSpecification CreateNewFrame() {
            return this;
        }

        internal System.Int32 Fac_Int32_GetIntValue(
                Phx.Inject.Tests.ConstructedChildInjector.SpecContainerCollection specContainers
        ) {
            return instance.GetIntValue();
        }
    }
}
#nullable restore
