//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data {
    internal class CustomNamedInjector_CommonTestValueSpecification {

        internal CustomNamedInjector_CommonTestValueSpecification CreateNewFrame() {
            return this;
        }

        internal System.Int32 Fac_A_Phx_Inject_Tests_Data_Model_QualifierAAttribute_Int32_GetIntQualifierA(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.CommonTestValueSpecification.GetIntQualifierA();
        }

        internal System.Int32 Fac_Int32_GetInt(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.CommonTestValueSpecification.GetInt();
        }

        internal System.Int32 Fac_L_LabelA_Int32_GetIntLabelA(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.CommonTestValueSpecification.GetIntLabelA();
        }

        internal System.String Fac_L_LabelA_String_GetStringLabelA(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.CommonTestValueSpecification.GetStringLabelA();
        }

        internal Phx.Inject.Tests.Data.Model.OuterType Fac_OuterType_GetOuterType(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.CommonTestValueSpecification.GetOuterType(
                specContainers.CustomNamedInjector_CustomNamedInjector_ConstructorFactories.CtorFac_AutoType_AutoType(specContainers),
                specContainers.CustomNamedInjector_CustomNamedInjector_ConstructorFactories.CtorFac_AutoTypeWithRequiredProperties_AutoTypeWithRequiredProperties(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.TestGenericObject<System.Int32> Fac_TestGenericObject_GetGenericObject(
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.CommonTestValueSpecification.GetGenericObject(
                specContainers.CustomNamedInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers));
        }

        internal void Bld_L_LabelA_TestBuilderObject_BuildTestBuilderObjectLabelA(
                Phx.Inject.Tests.Data.Model.TestBuilderObject target,
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            Phx.Inject.Tests.Data.CommonTestValueSpecification.BuildTestBuilderObjectLabelA(
                target,
                specContainers.CustomNamedInjector_CommonTestValueSpecification.Fac_L_LabelA_Int32_GetIntLabelA(specContainers));
        }

        internal void Bld_TestBuilderObject_BuildTestBuilderObject(
                Phx.Inject.Tests.Data.Model.TestBuilderObject target,
                Phx.Inject.Tests.CustomNamedInjector.SpecContainerCollection specContainers
        ) {
            Phx.Inject.Tests.Data.CommonTestValueSpecification.BuildTestBuilderObject(
                target,
                specContainers.CustomNamedInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers));
        }
    }
}
#nullable restore
