//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedQualifierTestInjector : Phx.Inject.Tests.IQualifierTestInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedQualifierTestInjector_QualifierSpecification GeneratedQualifierTestInjector_QualifierSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedQualifierTestInjector_QualifierSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedQualifierTestInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedQualifierTestInjector_QualifierSpecification: new Phx.Inject.Tests.GeneratedQualifierTestInjector_QualifierSpecification());
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetAttributeNamedLeafA() {
            return specContainers.GeneratedQualifierTestInjector_QualifierSpecification.GetAttributeNamedLeafA(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetAttributeNamedLeafB() {
            return specContainers.GeneratedQualifierTestInjector_QualifierSpecification.GetAttributeNamedLeafB(specContainers);
        }
    }
}
#nullable restore
