//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class AutoDependencyTestInjector : Phx.Inject.Tests.IAutoDependencyTestInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.AutoDependencyTestInjector_IAutoDependencyTestInjector_ConstructorFactories AutoDependencyTestInjector_IAutoDependencyTestInjector_ConstructorFactories,
                Phx.Inject.Tests.Data.AutoDependencyTestInjector_CommonTestValueSpecification AutoDependencyTestInjector_CommonTestValueSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        AutoDependencyTestInjector_IAutoDependencyTestInjector_ConstructorFactories.CreateNewFrame(),
                        AutoDependencyTestInjector_CommonTestValueSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public AutoDependencyTestInjector() {
            specContainers = new SpecContainerCollection(
                    AutoDependencyTestInjector_IAutoDependencyTestInjector_ConstructorFactories: new Phx.Inject.Tests.AutoDependencyTestInjector_IAutoDependencyTestInjector_ConstructorFactories(),
                    AutoDependencyTestInjector_CommonTestValueSpecification: new Phx.Inject.Tests.Data.AutoDependencyTestInjector_CommonTestValueSpecification());
        }

        public void BuildAutoBuilderType(Phx.Inject.Tests.Data.Model.AutoBuilderType target) {
            specContainers.AutoDependencyTestInjector_IAutoDependencyTestInjector_ConstructorFactories.DirBld_AutoBuilderType_Build(target, specContainers);
        }

        public void BuildLabeledAutoBuilderType(Phx.Inject.Tests.Data.Model.AutoBuilderType target) {
            specContainers.AutoDependencyTestInjector_IAutoDependencyTestInjector_ConstructorFactories.DirBld_L_AutoBuilderType_AutoBuilderType_BuildCustomLabel(target, specContainers);
        }

        public Phx.Inject.Tests.Data.Model.AutoBuilderType GetAutoBuilderType() {
            return specContainers.AutoDependencyTestInjector_IAutoDependencyTestInjector_ConstructorFactories.CtorFac_AutoBuilderType_AutoBuilderType(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.OuterType GetOuterType() {
            return specContainers.AutoDependencyTestInjector_CommonTestValueSpecification.Fac_OuterType_GetOuterType(specContainers);
        }
    }
}
#nullable restore
