//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class ConstructedChildInjector_NonConstructedSpecification {

        internal ConstructedChildInjector_NonConstructedSpecification CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf GetIntLeaf(
                Phx.Inject.Tests.ConstructedChildInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.NonConstructedSpecification.GetIntLeaf(
                specContainers.ConstructedChildInjector_IConstructedSpecification.GetIntValue(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.OuterType GetOuterType(
                Phx.Inject.Tests.ConstructedChildInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.NonConstructedSpecification.GetOuterType(
                specContainers.ConstructedChildInjector_ConstructedChildInjector_ConstructorFactories.GetConstructorautoType(specContainers));
        }
    }
}
#nullable restore
