//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedParentInjector_IChildDependencies : Phx.Inject.Tests.IChildDependencies {
        private readonly Phx.Inject.Tests.GeneratedParentInjector.SpecContainerCollection specContainers;

        public GeneratedParentInjector_IChildDependencies(Phx.Inject.Tests.GeneratedParentInjector.SpecContainerCollection specContainers) {
            this.specContainers = specContainers;
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetLeftLeaf() {
            return specContainers.GeneratedParentInjector_ParentSpecification.Fac_L_Left_ILeaf_GetLeftLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetRightLeaf() {
            return specContainers.GeneratedParentInjector_ParentSpecification.Fac_L_Right_ILeaf_GetRightLeaf(specContainers);
        }
    }
}
#nullable restore
