//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class InjectorScopeTestInjector_InjectorScopeSpecification {
        private System.Int32? scoped_Int32;

        internal InjectorScopeTestInjector_InjectorScopeSpecification CreateNewFrame() {
            return this;
        }

        internal System.Int32 Fac_Int32_GetIntDefault(
                Phx.Inject.Tests.InjectorScopeTestInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.InjectorScopeSpecification.GetIntDefault();
        }

        internal System.Int32 Fac_Recurrent_Int32_GetIntRecurrent(
                Phx.Inject.Tests.InjectorScopeTestInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.InjectorScopeSpecification.GetIntRecurrent();
        }

        internal System.Int32 Fac_Scoped_Int32_GetIntScoped(
                Phx.Inject.Tests.InjectorScopeTestInjector.SpecContainerCollection specContainers
        ) {
            return scoped_Int32 ??= Phx.Inject.Tests.InjectorScopeSpecification.GetIntScoped();
        }
    }
}
#nullable restore
