//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class LinkTestInjector : Phx.Inject.Tests.ILinkTestInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.Data.LinkTestInjector_CommonTestValueSpecification LinkTestInjector_CommonTestValueSpecification,
                Phx.Inject.Tests.LinkTestInjector_LinkTestInjector_ConstructorFactories LinkTestInjector_LinkTestInjector_ConstructorFactories
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        LinkTestInjector_CommonTestValueSpecification.CreateNewFrame(),
                        LinkTestInjector_LinkTestInjector_ConstructorFactories.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public LinkTestInjector() {
            specContainers = new SpecContainerCollection(
                    LinkTestInjector_CommonTestValueSpecification: new Phx.Inject.Tests.Data.LinkTestInjector_CommonTestValueSpecification(),
                    LinkTestInjector_LinkTestInjector_ConstructorFactories: new Phx.Inject.Tests.LinkTestInjector_LinkTestInjector_ConstructorFactories());
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetLinkedType() {
            return specContainers.LinkTestInjector_LinkTestInjector_ConstructorFactories.CtorFac_IntLeaf_IntLeaf(specContainers);
        }
    }
}
#nullable restore
