//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedChildInjector_IGrandchildDependencies : Phx.Inject.Tests.IGrandchildDependencies {
        private readonly Phx.Inject.Tests.GeneratedChildInjector.SpecContainerCollection specContainers;

        public GeneratedChildInjector_IGrandchildDependencies(Phx.Inject.Tests.GeneratedChildInjector.SpecContainerCollection specContainers) {
            this.specContainers = specContainers;
        }

        public Phx.Inject.Tests.Data.Model.Node GetNode() {
            return specContainers.GeneratedChildInjector_ChildSpecification.Fac_Node_GetNode(specContainers);
        }
    }
}
#nullable restore
