//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Inject {
    internal partial class GeneratedRawInjector : Phx.Inject.Tests.Data.Inject.IRawInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.Data.Specification.GeneratedRawInjector_RootSpecification GeneratedRawInjector_RootSpecification,
                Phx.Inject.Tests.Data.Specification.GeneratedRawInjector_LazySpecification GeneratedRawInjector_LazySpecification,
                Phx.Inject.Tests.Data.Specification.GeneratedRawInjector_LeafSpecification GeneratedRawInjector_LeafSpecification,
                Phx.Inject.Tests.Data.Specification.GeneratedRawInjector_LeafLinks GeneratedRawInjector_LeafLinks
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedRawInjector_RootSpecification.CreateNewFrame(),
                        GeneratedRawInjector_LazySpecification.CreateNewFrame(),
                        GeneratedRawInjector_LeafSpecification.CreateNewFrame(),
                        GeneratedRawInjector_LeafLinks.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedRawInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedRawInjector_RootSpecification: new Phx.Inject.Tests.Data.Specification.GeneratedRawInjector_RootSpecification(),
                    GeneratedRawInjector_LazySpecification: new Phx.Inject.Tests.Data.Specification.GeneratedRawInjector_LazySpecification(),
                    GeneratedRawInjector_LeafSpecification: new Phx.Inject.Tests.Data.Specification.GeneratedRawInjector_LeafSpecification(),
                    GeneratedRawInjector_LeafLinks: new Phx.Inject.Tests.Data.Specification.GeneratedRawInjector_LeafLinks());
        }

        public Phx.Inject.Tests.Data.Model.Root GetRoot() {
            return specContainers.GeneratedRawInjector_RootSpecification.GetRoot(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.Node GetNode() {
            return specContainers.GeneratedRawInjector_RootSpecification.GetNode(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.IntLeaf GetIntLeaf() {
            return specContainers.GeneratedRawInjector_LeafSpecification.GetIntLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.StringLeaf GetStringLeaf() {
            return specContainers.GeneratedRawInjector_LeafSpecification.GetStringLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ParametricLeaf<System.Int32> GetParametricLeaf() {
            return specContainers.GeneratedRawInjector_LeafSpecification.GetParametricLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetILeaf() {
            return specContainers.GeneratedRawInjector_LeafSpecification.GetStringLeaf(specContainers);
        }

        public void Build(Phx.Inject.Tests.Data.Model.LazyType target) {
            specContainers.GeneratedRawInjector_LazySpecification.BuildLazyType(target, specContainers);
        }
    }
}
#nullable restore
