//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedFactoryReferenceInjector_FactoryReferenceSpec {
        private Phx.Inject.Tests.Data.Model.StringLeaf? stringLeaf;
        private Phx.Inject.Tests.Data.Model.IntLeaf? intLeaf;

        internal GeneratedFactoryReferenceInjector_FactoryReferenceSpec CreateNewFrame() {
            return this;
        }

        internal System.Int32 PropFac_Int32_IntValue(
                Phx.Inject.Tests.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.FactoryReferenceSpec.IntValue;
        }

        internal System.String PropFac_String_StringValue(
                Phx.Inject.Tests.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.FactoryReferenceSpec.StringValue;
        }

        internal Phx.Inject.Tests.Data.Model.StringLeaf RefFac_StringLeaf_GetStringLeaf(
                Phx.Inject.Tests.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers
        ) {
            return stringLeaf ??= Phx.Inject.Tests.FactoryReferenceSpec.GetStringLeaf(
                specContainers.GeneratedFactoryReferenceInjector_FactoryReferenceSpec.PropFac_String_StringValue(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf RefFac_IntLeaf_GetIntLeaf(
                Phx.Inject.Tests.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers
        ) {
            return intLeaf ??= Phx.Inject.Tests.FactoryReferenceSpec.GetIntLeaf(
                specContainers.GeneratedFactoryReferenceInjector_FactoryReferenceSpec.PropFac_Int32_IntValue(specContainers));
        }
    }
}
#nullable restore
