//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedParentInjector_ParentSpecification {

        internal GeneratedParentInjector_ParentSpecification CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf Fac_L_Left_ILeaf_GetLeftLeaf(
                Phx.Inject.Tests.GeneratedParentInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.ParentSpecification.GetLeftLeaf();
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf Fac_L_Right_ILeaf_GetRightLeaf(
                Phx.Inject.Tests.GeneratedParentInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.ParentSpecification.GetRightLeaf();
        }
    }
}
#nullable restore
