//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories {
        private Phx.Inject.Tests.Data.Model.AutoTypeWithFabricationMode? autoTypeWithFabricationMode;

        internal AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.AutoBuilderType CtorFac_AutoBuilderType_AutoBuilderType(
                Phx.Inject.Tests.AutoDependencyTestInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.AutoBuilderType();
        }

        internal Phx.Inject.Tests.Data.Model.AutoType CtorFac_AutoType_AutoType(
                Phx.Inject.Tests.AutoDependencyTestInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.AutoType(
                specContainers.AutoDependencyTestInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers),
                specContainers.AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories.CtorFac_AutoTypeWithFabricationMode_AutoTypeWithFabricationMode(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.AutoTypeWithRequiredProperties CtorFac_AutoTypeWithRequiredProperties_AutoTypeWithRequiredProperties(
                Phx.Inject.Tests.AutoDependencyTestInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.AutoTypeWithRequiredProperties(
                specContainers.AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories.CtorFac_AutoType_AutoType(specContainers)
            ) {
                X = specContainers.AutoDependencyTestInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers),
                Y = specContainers.AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories.CtorFac_AutoTypeWithFabricationMode_AutoTypeWithFabricationMode(specContainers)
            };
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf CtorFac_IntLeaf_IntLeaf(
                Phx.Inject.Tests.AutoDependencyTestInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.IntLeaf(
                specContainers.AutoDependencyTestInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.AutoTypeWithFabricationMode CtorFac_AutoTypeWithFabricationMode_AutoTypeWithFabricationMode(
                Phx.Inject.Tests.AutoDependencyTestInjector.SpecContainerCollection specContainers
        ) {
            return autoTypeWithFabricationMode ??= new Phx.Inject.Tests.Data.Model.AutoTypeWithFabricationMode(
                specContainers.AutoDependencyTestInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers));
        }

        internal void DirBld_AutoBuilderType_Build(
                Phx.Inject.Tests.Data.Model.AutoBuilderType target,
                Phx.Inject.Tests.AutoDependencyTestInjector.SpecContainerCollection specContainers
        ) {
            Phx.Inject.Tests.Data.Model.AutoBuilderType.Build(
                target,
                specContainers.AutoDependencyTestInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers));
        }

        internal void DirBld_AutoBuilderType_AutoBuilderType_BuildCustomLabel(
                Phx.Inject.Tests.Data.Model.AutoBuilderType target,
                Phx.Inject.Tests.AutoDependencyTestInjector.SpecContainerCollection specContainers
        ) {
            Phx.Inject.Tests.Data.Model.AutoBuilderType.BuildCustomLabel(
                target,
                specContainers.AutoDependencyTestInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers));
        }
    }
}
#nullable restore
