//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedDefaultNamedInjector_CommonTestValueSpecification {

        internal GeneratedDefaultNamedInjector_CommonTestValueSpecification CreateNewFrame() {
            return this;
        }

        internal System.Int32 GetInt(
                Phx.Inject.Tests.GeneratedDefaultNamedInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.CommonTestValueSpecification.GetInt();
        }

        internal System.Int32 GetIntLabelA(
                Phx.Inject.Tests.GeneratedDefaultNamedInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.CommonTestValueSpecification.GetIntLabelA();
        }

        internal System.String GetStringLabelA(
                Phx.Inject.Tests.GeneratedDefaultNamedInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.CommonTestValueSpecification.GetStringLabelA();
        }
    }
}
#nullable restore
