//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedFactoryReferenceInjector : Phx.Inject.Tests.IFactoryReferenceInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedFactoryReferenceInjector_FactoryReferenceSpec GeneratedFactoryReferenceInjector_FactoryReferenceSpec
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedFactoryReferenceInjector_FactoryReferenceSpec.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedFactoryReferenceInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedFactoryReferenceInjector_FactoryReferenceSpec: new Phx.Inject.Tests.GeneratedFactoryReferenceInjector_FactoryReferenceSpec());
        }

        public Phx.Inject.Tests.Data.Model.IntLeaf GetIntLeaf() {
            return specContainers.GeneratedFactoryReferenceInjector_FactoryReferenceSpec.RefFac_IntLeaf_GetIntLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.StringLeaf GetStringLeaf() {
            return specContainers.GeneratedFactoryReferenceInjector_FactoryReferenceSpec.RefFac_StringLeaf_GetStringLeaf(specContainers);
        }
    }
}
#nullable restore
