//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class AutoDependencyTestInjector : Phx.Inject.Tests.IAutoDependencyTestInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.Data.AutoDependencyTestInjector_CommonTestValueSpecification AutoDependencyTestInjector_CommonTestValueSpecification,
                Phx.Inject.Tests.AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        AutoDependencyTestInjector_CommonTestValueSpecification.CreateNewFrame(),
                        AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public AutoDependencyTestInjector() {
            specContainers = new SpecContainerCollection(
                    AutoDependencyTestInjector_CommonTestValueSpecification: new Phx.Inject.Tests.Data.AutoDependencyTestInjector_CommonTestValueSpecification(),
                    AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories: new Phx.Inject.Tests.AutoDependencyTestInjector_AutoDependencyTestInjector_ConstructorFactories());
        }

        public Phx.Inject.Tests.Data.Model.OuterType GetOuterType() {
            return specContainers.AutoDependencyTestInjector_CommonTestValueSpecification.GetOuterType(specContainers);
        }
    }
}
#nullable restore
