//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class BuilderTestInjector : Phx.Inject.Tests.IBuilderTestInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.BuilderTestInjector_IBuilderTestInjector_ConstructorFactories BuilderTestInjector_IBuilderTestInjector_ConstructorFactories,
                Phx.Inject.Tests.Data.BuilderTestInjector_CommonTestValueSpecification BuilderTestInjector_CommonTestValueSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        BuilderTestInjector_IBuilderTestInjector_ConstructorFactories.CreateNewFrame(),
                        BuilderTestInjector_CommonTestValueSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public BuilderTestInjector() {
            specContainers = new SpecContainerCollection(
                    BuilderTestInjector_IBuilderTestInjector_ConstructorFactories: new Phx.Inject.Tests.BuilderTestInjector_IBuilderTestInjector_ConstructorFactories(),
                    BuilderTestInjector_CommonTestValueSpecification: new Phx.Inject.Tests.Data.BuilderTestInjector_CommonTestValueSpecification());
        }

        public void BuildTestBuilder(Phx.Inject.Tests.Data.Model.TestBuilderObject target) {
            specContainers.BuilderTestInjector_CommonTestValueSpecification.Bld_TestBuilderObject_BuildTestBuilderObject(target, specContainers);
        }

        public void BuildTestBuilderLabelA(Phx.Inject.Tests.Data.Model.TestBuilderObject target) {
            specContainers.BuilderTestInjector_CommonTestValueSpecification.Bld_L_LabelA_TestBuilderObject_BuildTestBuilderObjectLabelA(target, specContainers);
        }
    }
}
#nullable restore
