//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedNestedSpecInjector_OuterNestedSpecification_Inner {

        internal GeneratedNestedSpecInjector_OuterNestedSpecification_Inner CreateNewFrame() {
            return this;
        }

        internal System.Int32 GetIntValue(
                Phx.Inject.Tests.GeneratedNestedSpecInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.OuterNestedSpecification.Inner.GetIntValue();
        }
    }
}
#nullable restore
