//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedChildInjector_ChildSpecification {

        internal GeneratedChildInjector_ChildSpecification CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.Node Fac_Node_GetNode(
                Phx.Inject.Tests.GeneratedChildInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.ChildSpecification.GetNode(
                specContainers.GeneratedChildInjector_IChildDependencies.Fac_Left_ILeaf_GetLeftLeaf(specContainers),
                specContainers.GeneratedChildInjector_IChildDependencies.Fac_Right_ILeaf_GetRightLeaf(specContainers));
        }
    }
}
#nullable restore
