//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedRuntimeFactoryInjector_RuntimeFactorySpecification {

        internal GeneratedRuntimeFactoryInjector_RuntimeFactorySpecification CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf GetLeaf(
                Phx.Inject.Tests.GeneratedRuntimeFactoryInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.RuntimeFactorySpecification.GetLeaf();
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf GetLabeledLeaf(
                Phx.Inject.Tests.GeneratedRuntimeFactoryInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.RuntimeFactorySpecification.GetLabeledLeaf();
        }

        internal Phx.Inject.Tests.Data.Model.LeafFactory GetLeafFactory(
                Phx.Inject.Tests.GeneratedRuntimeFactoryInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.RuntimeFactorySpecification.GetLeafFactory(
                new Phx.Inject.Factory<Phx.Inject.Tests.Data.Model.ILeaf>(() => specContainers.GeneratedRuntimeFactoryInjector_RuntimeFactorySpecification.GetLeaf(specContainers)));
        }

        internal Phx.Inject.Tests.Data.Model.LeafFactory GetLabeledLeafFactory(
                Phx.Inject.Tests.GeneratedRuntimeFactoryInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.RuntimeFactorySpecification.GetLabeledLeafFactory(
                new Phx.Inject.Factory<Phx.Inject.Tests.Data.Model.ILeaf>(() => specContainers.GeneratedRuntimeFactoryInjector_RuntimeFactorySpecification.GetLabeledLeaf(specContainers)));
        }
    }
}
#nullable restore
