//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class InjectorProviderTestInjector : Phx.Inject.Tests.IInjectorProviderTestInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.InjectorProviderTestInjector_InjectorProviderTestInjector_ConstructorFactories InjectorProviderTestInjector_InjectorProviderTestInjector_ConstructorFactories,
                Phx.Inject.Tests.Data.InjectorProviderTestInjector_CommonTestValueSpecification InjectorProviderTestInjector_CommonTestValueSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        InjectorProviderTestInjector_InjectorProviderTestInjector_ConstructorFactories.CreateNewFrame(),
                        InjectorProviderTestInjector_CommonTestValueSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public InjectorProviderTestInjector() {
            specContainers = new SpecContainerCollection(
                    InjectorProviderTestInjector_InjectorProviderTestInjector_ConstructorFactories: new Phx.Inject.Tests.InjectorProviderTestInjector_InjectorProviderTestInjector_ConstructorFactories(),
                    InjectorProviderTestInjector_CommonTestValueSpecification: new Phx.Inject.Tests.Data.InjectorProviderTestInjector_CommonTestValueSpecification());
        }

        public System.Int32 GetInt() {
            return specContainers.InjectorProviderTestInjector_CommonTestValueSpecification.Fac_Int32_GetInt(specContainers);
        }

        public System.Int32 GetLabelAInt() {
            return specContainers.InjectorProviderTestInjector_CommonTestValueSpecification.Fac_L_LabelA_Int32_GetIntLabelA(specContainers);
        }

        public System.String GetlabelAString() {
            return specContainers.InjectorProviderTestInjector_CommonTestValueSpecification.Fac_L_LabelA_String_GetStringLabelA(specContainers);
        }

        public System.Int32 GetIntQualifierA() {
            return specContainers.InjectorProviderTestInjector_CommonTestValueSpecification.Fac_A_Phx_Inject_Tests_Data_Model_QualifierAAttribute_Int32_GetIntQualifierA(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.TestGenericObject<System.Int32> GetGenericObject() {
            return specContainers.InjectorProviderTestInjector_CommonTestValueSpecification.Fac_TestGenericObject_GetGenericObject(specContainers);
        }
    }
}
#nullable restore
