//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.2.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedChildInjector_IChildDependencies {
        private readonly Phx.Inject.Tests.IChildDependencies instance;

        public GeneratedChildInjector_IChildDependencies(Phx.Inject.Tests.IChildDependencies instance) {
            this.instance = instance;
        }

        internal GeneratedChildInjector_IChildDependencies CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf Fac_Left_ILeaf_GetLeftLeaf(
                Phx.Inject.Tests.GeneratedChildInjector.SpecContainerCollection specContainers
        ) {
            return instance.GetLeftLeaf();
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf Fac_Right_ILeaf_GetRightLeaf(
                Phx.Inject.Tests.GeneratedChildInjector.SpecContainerCollection specContainers
        ) {
            return instance.GetRightLeaf();
        }
    }
}
#nullable restore
