//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class GeneratedPropertyFactoryInjector_PropertyFactoryStaticSpec {

        internal GeneratedPropertyFactoryInjector_PropertyFactoryStaticSpec CreateNewFrame() {
            var newFrame = new GeneratedPropertyFactoryInjector_PropertyFactoryStaticSpec();
            return newFrame;
        }

        internal Phx.Inject.Tests.Data.Model.StringLeaf GetPropertyStringLeaf(
                Phx.Inject.Tests.Data.Inject.GeneratedPropertyFactoryInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.PropertyFactoryStaticSpec.StringLeaf;
        }
    }
}
#nullable restore
