//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class ConstructedParentInjector : Phx.Inject.Tests.IConstructedParentInjector {
        internal record SpecContainerCollection (
        
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return this;
            }
        }

        private readonly SpecContainerCollection specContainers;

        public ConstructedParentInjector() {
            specContainers = new SpecContainerCollection(
            );
        }

        public Phx.Inject.Tests.IConstructedChildInjector GetChildInjector(
                Phx.Inject.Tests.IConstructedSpecification iConstructedSpecification
        ) {
            return new Phx.Inject.Tests.ConstructedChildInjector(
                    iConstructedSpecification: iConstructedSpecification);
        }
    }
}
#nullable restore
