//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedMultiBindInjector : Phx.Inject.Tests.IMultiBindInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedMultiBindInjector_MultiBindSpecification GeneratedMultiBindInjector_MultiBindSpecification
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedMultiBindInjector_MultiBindSpecification.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedMultiBindInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedMultiBindInjector_MultiBindSpecification: new Phx.Inject.Tests.GeneratedMultiBindInjector_MultiBindSpecification());
        }

        public System.Collections.Generic.IReadOnlyList<Phx.Inject.Tests.Data.Model.ILeaf> GetLeafList() {
            return Phx.Inject.InjectionUtil.Combine<Phx.Inject.Tests.Data.Model.ILeaf>(
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlyList_GetListLeaf1(specContainers),
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlyList_GetListLeaf2(specContainers)
            );
        }

        public System.Collections.Generic.ISet<Phx.Inject.Tests.Data.Model.ILeaf> GetLeafSet() {
            return Phx.Inject.InjectionUtil.Combine<Phx.Inject.Tests.Data.Model.ILeaf>(
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_ISet_GetSetLeaf1(specContainers),
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_ISet_GetSetLeaf2(specContainers)
            );
        }

        public System.Collections.Generic.IReadOnlySet<Phx.Inject.Tests.Data.Model.ILeaf> GetLeafSetReadOnly() {
            return System.Collections.Immutable.ImmutableHashSet.CreateRange<Phx.Inject.Tests.Data.Model.ILeaf>(
                Phx.Inject.InjectionUtil.CombineReadOnlySet<Phx.Inject.Tests.Data.Model.ILeaf>(
                    specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlySet_GetSetLeaf1ReadOnly(specContainers),
                    specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlySet_GetSetLeaf2ReadOnly(specContainers))
            );
        }

        public System.Collections.Generic.IReadOnlyDictionary<System.String,Phx.Inject.Tests.Data.Model.ILeaf> GetLeafDict() {
            return Phx.Inject.InjectionUtil.Combine<System.String, Phx.Inject.Tests.Data.Model.ILeaf>(
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlyDictionary_GetDictLeaf1(specContainers),
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlyDictionary_GetDictLeaf2(specContainers)
            );
        }

        public Phx.Inject.Factory<System.Collections.Generic.IReadOnlyList<Phx.Inject.Tests.Data.Model.ILeaf>> GetLeafListRuntimeFactory() {
            return new Phx.Inject.Factory<System.Collections.Generic.IReadOnlyList<Phx.Inject.Tests.Data.Model.ILeaf>>(() => Phx.Inject.InjectionUtil.Combine<Phx.Inject.Tests.Data.Model.ILeaf>(
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlyList_GetListLeaf1(specContainers),
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlyList_GetListLeaf2(specContainers)
            ));
        }

        public Phx.Inject.Factory<System.Collections.Generic.ISet<Phx.Inject.Tests.Data.Model.ILeaf>> GetLeafSetRuntimeFactory() {
            return new Phx.Inject.Factory<System.Collections.Generic.ISet<Phx.Inject.Tests.Data.Model.ILeaf>>(() => Phx.Inject.InjectionUtil.Combine<Phx.Inject.Tests.Data.Model.ILeaf>(
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_ISet_GetSetLeaf1(specContainers),
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_ISet_GetSetLeaf2(specContainers)
            ));
        }

        public Phx.Inject.Factory<System.Collections.Generic.IReadOnlyDictionary<System.String,Phx.Inject.Tests.Data.Model.ILeaf>> GetLeafDictRuntimeFactory() {
            return new Phx.Inject.Factory<System.Collections.Generic.IReadOnlyDictionary<System.String,Phx.Inject.Tests.Data.Model.ILeaf>>(() => Phx.Inject.InjectionUtil.Combine<System.String, Phx.Inject.Tests.Data.Model.ILeaf>(
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlyDictionary_GetDictLeaf1(specContainers),
                specContainers.GeneratedMultiBindInjector_MultiBindSpecification.Fac_IReadOnlyDictionary_GetDictLeaf2(specContainers)
            ));
        }
    }
}
#nullable restore
