//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class InjectorProviderTestInjector_InjectorProviderTestInjector_ConstructorFactories {

        internal InjectorProviderTestInjector_InjectorProviderTestInjector_ConstructorFactories CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf GetConstructorintLeaf(
                Phx.Inject.Tests.InjectorProviderTestInjector.SpecContainerCollection specContainers
        ) {
            return new Phx.Inject.Tests.Data.Model.IntLeaf(
                specContainers.InjectorProviderTestInjector_CommonTestValueSpecification.GetInt(specContainers));
        }
    }
}
#nullable restore
