//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.External {
    internal class GeneratedChildInjector_IChildExternalDependencies {
        private readonly Phx.Inject.Tests.Data.External.IChildExternalDependencies instance;

        public GeneratedChildInjector_IChildExternalDependencies(Phx.Inject.Tests.Data.External.IChildExternalDependencies instance) {
            this.instance = instance;
        }

        internal GeneratedChildInjector_IChildExternalDependencies CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf GetLeftLeaf(
                Phx.Inject.Tests.Data.Inject.GeneratedChildInjector.SpecContainerCollection specContainers
        ) {
            return instance.GetLeftLeaf();
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf GetRightLeaf(
                Phx.Inject.Tests.Data.Inject.GeneratedChildInjector.SpecContainerCollection specContainers
        ) {
            return instance.GetRightLeaf();
        }
    }
}
#nullable restore
