//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedRuntimeFactoryInjector_RuntimeFactorySpecification {

        internal GeneratedRuntimeFactoryInjector_RuntimeFactorySpecification CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf Fac_ILeaf_GetLeaf(
                Phx.Inject.Tests.GeneratedRuntimeFactoryInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.RuntimeFactorySpecification.GetLeaf();
        }

        internal Phx.Inject.Tests.Data.Model.ILeaf Fac_LabeledLeaf_ILeaf_GetLabeledLeaf(
                Phx.Inject.Tests.GeneratedRuntimeFactoryInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.RuntimeFactorySpecification.GetLabeledLeaf();
        }

        internal Phx.Inject.Tests.Data.Model.LeafFactory Fac_LeafFactory_GetLeafFactory(
                Phx.Inject.Tests.GeneratedRuntimeFactoryInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.RuntimeFactorySpecification.GetLeafFactory(
                new Phx.Inject.Factory<Phx.Inject.Tests.Data.Model.ILeaf>(() => specContainers.GeneratedRuntimeFactoryInjector_RuntimeFactorySpecification.Fac_ILeaf_GetLeaf(specContainers)));
        }

        internal Phx.Inject.Tests.Data.Model.LeafFactory Fac_LabeledLeaf_LeafFactory_GetLabeledLeafFactory(
                Phx.Inject.Tests.GeneratedRuntimeFactoryInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.RuntimeFactorySpecification.GetLabeledLeafFactory(
                new Phx.Inject.Factory<Phx.Inject.Tests.Data.Model.ILeaf>(() => specContainers.GeneratedRuntimeFactoryInjector_RuntimeFactorySpecification.Fac_LabeledLeaf_ILeaf_GetLabeledLeaf(specContainers)));
        }
    }
}
#nullable restore
