//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal class GeneratedGrandchildInjector_IGrandchildDependencies {
        private readonly Phx.Inject.Tests.IGrandchildDependencies instance;

        public GeneratedGrandchildInjector_IGrandchildDependencies(Phx.Inject.Tests.IGrandchildDependencies instance) {
            this.instance = instance;
        }

        internal GeneratedGrandchildInjector_IGrandchildDependencies CreateNewFrame() {
            return this;
        }

        internal Phx.Inject.Tests.Data.Model.Node PropFac_Node_Node(
                Phx.Inject.Tests.GeneratedGrandchildInjector.SpecContainerCollection specContainers
        ) {
            return instance.Node;
        }
    }
}
#nullable restore
