//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.9.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedChildInjector : Phx.Inject.Tests.IChildInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedChildInjector_ChildSpecification GeneratedChildInjector_ChildSpecification,
                Phx.Inject.Tests.GeneratedChildInjector_IChildDependencies GeneratedChildInjector_IChildDependencies
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedChildInjector_ChildSpecification.CreateNewFrame(),
                        GeneratedChildInjector_IChildDependencies.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedChildInjector(
                Phx.Inject.Tests.IChildDependencies iChildDependencies
        ) {
            specContainers = new SpecContainerCollection(
                    GeneratedChildInjector_ChildSpecification: new Phx.Inject.Tests.GeneratedChildInjector_ChildSpecification(),
                    GeneratedChildInjector_IChildDependencies: new Phx.Inject.Tests.GeneratedChildInjector_IChildDependencies(iChildDependencies));
        }

        public Phx.Inject.Tests.IGrandchildInjector GetGrandchildInjector() {
            return new Phx.Inject.Tests.GeneratedGrandchildInjector(
                    iGrandchildDependencies: new Phx.Inject.Tests.GeneratedChildInjector_IGrandchildDependencies(specContainers));
        }
    }
}
#nullable restore
