//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.6.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class GeneratedContainerInjector_ContainerSpecification {
        private System.Int32? int32;

        internal GeneratedContainerInjector_ContainerSpecification CreateNewFrame() {
            var newFrame = new GeneratedContainerInjector_ContainerSpecification();
            return newFrame;
        }

        internal System.Int32 GetInt(
                Phx.Inject.Tests.Data.Inject.GeneratedContainerInjector.SpecContainerCollection specContainers
        ) {
            return int32 ??= Phx.Inject.Tests.Data.Specification.ContainerSpecification.GetInt();
        }

        internal System.Collections.Generic.List<Phx.Inject.Tests.Data.Model.IntLeaf> GetIntLeaf1(
                Phx.Inject.Tests.Data.Inject.GeneratedContainerInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.ContainerSpecification.GetIntLeaf1(
                specContainers.GeneratedContainerInjector_GeneratedContainerInjector_ConstructorFactories.GetConstructorintLeaf(specContainers));
        }

        internal System.Collections.Generic.List<Phx.Inject.Tests.Data.Model.IntLeaf> GetIntLeaf2(
                Phx.Inject.Tests.Data.Inject.GeneratedContainerInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.ContainerSpecification.GetIntLeaf2(
                specContainers.GeneratedContainerInjector_GeneratedContainerInjector_ConstructorFactories.GetConstructorintLeaf(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.Node GetNode(
                Phx.Inject.Tests.Data.Inject.GeneratedContainerInjector.SpecContainerCollection parentSpecContainer
        ) {
            var specContainers = parentSpecContainer.CreateNewFrame();
            return Phx.Inject.Tests.Data.Specification.ContainerSpecification.GetNode(
                Phx.Inject.InjectionUtil.Combine<Phx.Inject.Tests.Data.Model.IntLeaf> (
                    specContainers.GeneratedContainerInjector_ContainerSpecification.GetIntLeaf1(specContainers),
                    specContainers.GeneratedContainerInjector_ContainerSpecification.GetIntLeaf2(specContainers)
                ));
        }
    }
}
#nullable restore
