//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.8.2.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests {
    internal partial class GeneratedChildInjector : Phx.Inject.Tests.IChildInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.GeneratedChildInjector_ChildSpecification GeneratedChildInjector_ChildSpecification,
                Phx.Inject.Tests.GeneratedChildInjector_IChildExternalDependencies GeneratedChildInjector_IChildExternalDependencies
        ) {
            internal SpecContainerCollection CreateNewFrame() {
                return new SpecContainerCollection(
                        GeneratedChildInjector_ChildSpecification.CreateNewFrame(),
                        GeneratedChildInjector_IChildExternalDependencies.CreateNewFrame());
            }
        }

        private readonly SpecContainerCollection specContainers;

        public GeneratedChildInjector(
                Phx.Inject.Tests.IChildExternalDependencies iChildExternalDependencies
        ) {
            specContainers = new SpecContainerCollection(
                    GeneratedChildInjector_ChildSpecification: new Phx.Inject.Tests.GeneratedChildInjector_ChildSpecification(),
                    GeneratedChildInjector_IChildExternalDependencies: new Phx.Inject.Tests.GeneratedChildInjector_IChildExternalDependencies(iChildExternalDependencies));
        }

        public Phx.Inject.Tests.IGrandchildInjector GetGrandchildInjector() {
            return new Phx.Inject.Tests.GeneratedGrandchildInjector(
                    iGrandchildExternalDependencies: new Phx.Inject.Tests.GeneratedChildInjector_IGrandchildExternalDependencies(specContainers));
        }
    }
}
#nullable restore
