//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.1.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class GeneratedGrandchildInjector_GrandchildSpecification {

        internal Phx.Inject.Tests.Data.Model.Root GetRoot(
                Phx.Inject.Tests.Data.Inject.GeneratedGrandchildInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.GrandchildSpecification.GetRoot(
                specContainers.GeneratedGrandchildInjector_IGrandchildExternalDependencies.GetNode(specContainers),
                specContainers.GeneratedGrandchildInjector_IGrandchildExternalDependencies.GetNode(specContainers));
        }
    }
}
#nullable restore
