//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.0.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class CustomInjector_LeafSpecification_LeafLinks {

        internal Phx.Inject.Tests.Data.Model.StringLeaf GetStringLeaf(
                Phx.Inject.Tests.Data.Inject.CustomInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.LeafSpecification.LeafLinks.GetStringLeaf();
        }
    }
}
#nullable restore
