//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.0.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Inject {
    internal partial class CustomInjector : Phx.Inject.Tests.Data.Inject.ITestInjector {
        internal interface ISpecContainerCollection {
            Phx.Inject.Tests.Data.Specification.CustomInjector_RootSpecificationContainer CustomInjector_RootSpecificationContainer { get; }
            Phx.Inject.Tests.Data.Specification.CustomInjector_LazySpecificationContainer CustomInjector_LazySpecificationContainer { get; }
            Phx.Inject.Tests.Data.Specification.CustomInjector_LeafSpecificationContainer CustomInjector_LeafSpecificationContainer { get; }
            Phx.Inject.Tests.Data.Specification.CustomInjector_LeafLinksContainer CustomInjector_LeafLinksContainer { get; }
        }

        internal class SpecContainerCollection: ISpecContainerCollection  {
            public Phx.Inject.Tests.Data.Specification.CustomInjector_RootSpecificationContainer CustomInjector_RootSpecificationContainer { get; } = new Phx.Inject.Tests.Data.Specification.CustomInjector_RootSpecificationContainer();
            public Phx.Inject.Tests.Data.Specification.CustomInjector_LazySpecificationContainer CustomInjector_LazySpecificationContainer { get; } = new Phx.Inject.Tests.Data.Specification.CustomInjector_LazySpecificationContainer();
            public Phx.Inject.Tests.Data.Specification.CustomInjector_LeafSpecificationContainer CustomInjector_LeafSpecificationContainer { get; } = new Phx.Inject.Tests.Data.Specification.CustomInjector_LeafSpecificationContainer();
            public Phx.Inject.Tests.Data.Specification.CustomInjector_LeafLinksContainer CustomInjector_LeafLinksContainer { get; } = new Phx.Inject.Tests.Data.Specification.CustomInjector_LeafLinksContainer();
        }

        private readonly ISpecContainerCollection specContainers = new SpecContainerCollection();

        public Phx.Inject.Tests.Data.Model.Root GetRoot() {
            return specContainers.CustomInjector_RootSpecificationContainer.GetRoot(specContainers);
        }

        public void Build(Phx.Inject.Tests.Data.Model.LazyType value) {
            specContainers.CustomInjector_LazySpecificationContainer.BuildLazyType(value, specContainers);
        }
    }
}
#nullable restore
