//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.0.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class GeneratedRawInjector_RootSpecificationContainer {
        private Phx.Inject.Tests.Data.Model.Root? rootInstance;

        internal Phx.Inject.Tests.Data.Model.Root GetRoot(Phx.Inject.Tests.Data.Inject.GeneratedRawInjector.ISpecContainerCollection specContainers) {
            return rootInstance ??= Phx.Inject.Tests.Data.Specification.RootSpecification.GetRoot(
                specContainers.GeneratedRawInjector_RootSpecificationContainer.GetNode(specContainers),
                specContainers.GeneratedRawInjector_RootSpecificationContainer.GetNode(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.Node GetNode(Phx.Inject.Tests.Data.Inject.GeneratedRawInjector.ISpecContainerCollection specContainers) {
            return Phx.Inject.Tests.Data.Specification.RootSpecification.GetNode(
                specContainers.GeneratedRawInjector_LeafSpecificationContainer.GetIntLeaf(specContainers),
                specContainers.GeneratedRawInjector_LeafSpecificationContainer.GetStringLeaf(specContainers));
        }

    }
}
#nullable restore
