//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.0.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class GeneratedRawInjector_LazySpecificationContainer {

        internal void BuildLazyType(Phx.Inject.Tests.Data.Model.LazyType value, Phx.Inject.Tests.Data.Inject.GeneratedRawInjector.ISpecContainerCollection specContainers) {
            Phx.Inject.Tests.Data.Specification.LazySpecification.BuildLazyType(
                value,
                specContainers.GeneratedRawInjector_LeafSpecificationContainer.GetStringLeaf(specContainers));
        }

    }
}
#nullable restore
