//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.3.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class GeneratedFactoryReferenceInjector_FactoryReferenceSpec {
        private Phx.Inject.Tests.Data.Model.StringLeaf? stringLeaf;
        private Phx.Inject.Tests.Data.Model.IntLeaf? intLeaf;

        internal System.Int32 GetPropertyIntValue(
                Phx.Inject.Tests.Data.Inject.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.FactoryReferenceSpec.IntValue;
        }

        internal System.String GetPropertyStringValue(
                Phx.Inject.Tests.Data.Inject.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.FactoryReferenceSpec.StringValue;
        }

        internal Phx.Inject.Tests.Data.Model.StringLeaf GetReferenceGetStringLeaf(
                Phx.Inject.Tests.Data.Inject.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers
        ) {
            return stringLeaf ??= Phx.Inject.Tests.Data.Specification.FactoryReferenceSpec.GetStringLeaf(
                specContainers.GeneratedFactoryReferenceInjector_FactoryReferenceSpec.GetPropertyStringValue(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.IntLeaf GetReferenceGetIntLeaf(
                Phx.Inject.Tests.Data.Inject.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers
        ) {
            return intLeaf ??= Phx.Inject.Tests.Data.Specification.FactoryReferenceSpec.GetIntLeaf(
                specContainers.GeneratedFactoryReferenceInjector_FactoryReferenceSpec.GetPropertyIntValue(specContainers));
        }

        internal void GetReferenceBuildLazyType(
        Phx.Inject.Tests.Data.Model.LazyType target, Phx.Inject.Tests.Data.Inject.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers) {
            Phx.Inject.Tests.Data.Specification.FactoryReferenceSpec.BuildLazyType(
                target,
                specContainers.GeneratedFactoryReferenceInjector_FactoryReferenceSpec.GetReferenceGetIntLeaf(specContainers));
        }

        internal void GetReferenceBuildLazyTypeField(
        Phx.Inject.Tests.Data.Model.LazyType target, Phx.Inject.Tests.Data.Inject.GeneratedFactoryReferenceInjector.SpecContainerCollection specContainers) {
            Phx.Inject.Tests.Data.Specification.FactoryReferenceSpec.BuildLazyTypeField(
                target,
                specContainers.GeneratedFactoryReferenceInjector_FactoryReferenceSpec.GetReferenceGetIntLeaf(specContainers));
        }
    }
}
#nullable restore
