//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.0.1.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Specification {
    internal class GeneratedRawInjector_RootSpecification {
        private Phx.Inject.Tests.Data.Model.Root? root;

        internal Phx.Inject.Tests.Data.Model.Root GetRoot(
                Phx.Inject.Tests.Data.Inject.GeneratedRawInjector.SpecContainerCollection specContainers
        ) {
            return root ??= Phx.Inject.Tests.Data.Specification.RootSpecification.GetRoot(
                specContainers.GeneratedRawInjector_RootSpecification.GetNode(specContainers),
                specContainers.GeneratedRawInjector_RootSpecification.GetNode(specContainers));
        }

        internal Phx.Inject.Tests.Data.Model.Node GetNode(
                Phx.Inject.Tests.Data.Inject.GeneratedRawInjector.SpecContainerCollection specContainers
        ) {
            return Phx.Inject.Tests.Data.Specification.RootSpecification.GetNode(
                specContainers.GeneratedRawInjector_LeafSpecification.GetIntLeaf(specContainers),
                specContainers.GeneratedRawInjector_LeafSpecification.GetStringLeaf(specContainers));
        }
    }
}
#nullable restore
