//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Inject {
    internal partial class GeneratedConstructedInjector : Phx.Inject.Tests.Data.Inject.IConstructedInjector {
        internal interface ISpecContainerCollection {
        }

        internal class SpecContainerCollection: ISpecContainerCollection  {
        }

        private readonly ISpecContainerCollection specContainers = new SpecContainerCollection();
    }
}
#nullable restore
