// -----------------------------------------------------------------------------
//  <copyright file="GeneratedFileTemplate.cs" company="Star Cruise Studios LLC">
//      Copyright (c) 2022 Star Cruise Studios LLC. All rights reserved.
//      Licensed under the Apache License 2.0 License.
//      See http://www.apache.org/licenses/LICENSE-2.0 for full license information.
//  </copyright>
// -----------------------------------------------------------------------------

namespace Phx.Inject.Generator.Model.Templates {
    using Microsoft.CodeAnalysis;

    internal record GeneratedFileTemplate(
            string NamespaceName,
            IRenderTemplate FileContentTemplate,
            Location Location
    ) : IRenderTemplate {
        public void Render(IRenderWriter writer) {
            var assemblyVersion = typeof(GeneratedFileTemplate).Assembly.GetName().Version.ToString();

            writer
                    .AppendLine("//------------------------------------------------------------------------------")
                    .AppendLine("// <auto-generated>")
                    .AppendLine($"//     This code was generated by Phx.Inject.Generator {assemblyVersion}.")
                    .AppendLine("//")
                    .AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if")
                    .AppendLine("//     the code is regenerated.")
                    .AppendLine("// </auto-generated>")
                    .AppendLine("//------------------------------------------------------------------------------")
                    .AppendBlankLine();
            if (writer.Settings.NullableEnabled) {
                writer.AppendLine("#nullable enable");
            }
            writer.AppendLine($"namespace {NamespaceName} {{")
                    .IncreaseIndent(1);

            FileContentTemplate.Render(writer);

            writer
                    .DecreaseIndent(1)
                    .AppendLine("}");
            if (writer.Settings.NullableEnabled) {
                writer.AppendLine("#nullable restore");
            }
        }
    };
}
