// -----------------------------------------------------------------------------
//  <copyright file="GeneratedFileTemplate.cs" company="Star Cruise Studios LLC">
//      Copyright (c) 2022 Star Cruise Studios LLC. All rights reserved.
//      Licensed under the Apache License 2.0 License.
//      See http://www.apache.org/licenses/LICENSE-2.0 for full license information.
//  </copyright>
// -----------------------------------------------------------------------------

namespace Phx.Inject.Generator.Render.Templates {
    internal record GeneratedFileTemplate(string NamespaceName, IRenderTemplate FileContentTemplate) : IRenderTemplate {
        public void Render(IRenderWriter writer) {
            writer
                .AppendLine("//------------------------------------------------------------------------------")
                .AppendLine("// <auto-generated>")
                .AppendLine("//     This code was generated by Phx.Inject.Generator.")
                .AppendLine("//")
                .AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if")
                .AppendLine("//     the code is regenerated.")
                .AppendLine("// </auto-generated>")
                .AppendLine("//------------------------------------------------------------------------------")
                .AppendBlankLine()
                .AppendLine("#nullable enable")
                .AppendLine($"namespace {NamespaceName} {{").IncreaseIndent(1);

            FileContentTemplate.Render(writer);

            writer
                .DecreaseIndent(1).AppendLine("}")
                .AppendLine("#nullable restore");
        }
    }
}