//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.5.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Inject {
    internal partial class GeneratedConstructedInjector : Phx.Inject.Tests.Data.Inject.IConstructedInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.Data.Specification.GeneratedConstructedInjector_IConstructedSpecification GeneratedConstructedInjector_IConstructedSpecification,
                Phx.Inject.Tests.Data.Specification.GeneratedConstructedInjector_NonConstructedSpecification GeneratedConstructedInjector_NonConstructedSpecification,
                Phx.Inject.Tests.Data.Inject.GeneratedConstructedInjector_GeneratedConstructedInjector_ConstructorFactories GeneratedConstructedInjector_GeneratedConstructedInjector_ConstructorFactories);

        private readonly SpecContainerCollection specContainers;

        public GeneratedConstructedInjector(
                Phx.Inject.Tests.Data.Specification.IConstructedSpecification iConstructedSpecification
        ) {
            specContainers = new SpecContainerCollection(
                    GeneratedConstructedInjector_IConstructedSpecification: new Phx.Inject.Tests.Data.Specification.GeneratedConstructedInjector_IConstructedSpecification(iConstructedSpecification),
                    GeneratedConstructedInjector_NonConstructedSpecification: new Phx.Inject.Tests.Data.Specification.GeneratedConstructedInjector_NonConstructedSpecification(),
                    GeneratedConstructedInjector_GeneratedConstructedInjector_ConstructorFactories: new Phx.Inject.Tests.Data.Inject.GeneratedConstructedInjector_GeneratedConstructedInjector_ConstructorFactories());
        }

        public Phx.Inject.Tests.Data.Model.IntLeaf GetIntLeaf() {
            return specContainers.GeneratedConstructedInjector_NonConstructedSpecification.GetIntLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.ILeaf GetILeaf() {
            return specContainers.GeneratedConstructedInjector_NonConstructedSpecification.GetIntLeaf(specContainers);
        }

        public Phx.Inject.Tests.Data.Model.OuterType GetOuterType() {
            return specContainers.GeneratedConstructedInjector_NonConstructedSpecification.GetOuterType(specContainers);
        }
    }
}
#nullable restore
