//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.4.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Inject {
    internal partial class GeneratedNestedSpecInjector : Phx.Inject.Tests.Data.Inject.INestedSpecInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.Data.Specification.GeneratedNestedSpecInjector_OuterNestedSpecification GeneratedNestedSpecInjector_OuterNestedSpecification,
                Phx.Inject.Tests.Data.Specification.GeneratedNestedSpecInjector_OuterNestedSpecification_Inner GeneratedNestedSpecInjector_OuterNestedSpecification_Inner);

        private readonly SpecContainerCollection specContainers;

        public GeneratedNestedSpecInjector() {
            specContainers = new SpecContainerCollection(
                    GeneratedNestedSpecInjector_OuterNestedSpecification: new Phx.Inject.Tests.Data.Specification.GeneratedNestedSpecInjector_OuterNestedSpecification(),
                    GeneratedNestedSpecInjector_OuterNestedSpecification_Inner: new Phx.Inject.Tests.Data.Specification.GeneratedNestedSpecInjector_OuterNestedSpecification_Inner());
        }

        public Phx.Inject.Tests.Data.Model.IntLeaf GetIntLeaf() {
            return specContainers.GeneratedNestedSpecInjector_OuterNestedSpecification.GetIntLeaf(specContainers);
        }
    }
}
#nullable restore
