//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Phx.Inject.Generator 0.4.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Phx.Inject.Tests.Data.Inject {
    internal partial class GeneratedChildInjector : Phx.Inject.Tests.Data.Inject.IChildInjector {
        internal record SpecContainerCollection (
                Phx.Inject.Tests.Data.Specification.GeneratedChildInjector_ChildSpecification GeneratedChildInjector_ChildSpecification,
                Phx.Inject.Tests.Data.External.GeneratedChildInjector_IChildExternalDependencies GeneratedChildInjector_IChildExternalDependencies);

        private readonly SpecContainerCollection specContainers;

        public GeneratedChildInjector(
                Phx.Inject.Tests.Data.External.IChildExternalDependencies iChildExternalDependencies
        ) {
            specContainers = new SpecContainerCollection(
                    GeneratedChildInjector_ChildSpecification: new Phx.Inject.Tests.Data.Specification.GeneratedChildInjector_ChildSpecification(),
                    GeneratedChildInjector_IChildExternalDependencies: new Phx.Inject.Tests.Data.External.GeneratedChildInjector_IChildExternalDependencies(iChildExternalDependencies));
        }

        public Phx.Inject.Tests.Data.Inject.IGrandchildInjector GetGrandchildInjector() {
            return new Phx.Inject.Tests.Data.Inject.GeneratedGrandchildInjector(
                    iGrandchildExternalDependencies: new Phx.Inject.Tests.Data.Inject.GeneratedChildInjector_IGrandchildExternalDependencies(specContainers));
        }
    }
}
#nullable restore
