// -----------------------------------------------------------------------------
// <copyright file="ClassElementValidator.cs" company="Star Cruise Studios LLC">
//     Copyright (c) 2026 Star Cruise Studios LLC. All rights reserved.
//     Licensed under the Apache License, Version 2.0.
//     See http://www.apache.org/licenses/LICENSE-2.0 for full license information.
// </copyright>
// -----------------------------------------------------------------------------

#region

using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Phx.Inject.Generator.Incremental.Stage1.Metadata.Pipeline.Attributes;

#endregion

namespace Phx.Inject.Generator.Incremental.Stage1.Metadata.Pipeline.Validators;

/// <summary>
///     Validates that a type symbol represents a class meeting specified structural requirements.
/// </summary>
/// <param name="requiredAccessibility">
///     The accessibility level required for the class. Defaults to Any (no accessibility constraint).
/// </param>
/// <param name="isStatic">
///     If non-null, specifies whether the class must be static (true) or non-static (false).
/// </param>
/// <param name="isAbstract">
///     If non-null, specifies whether the class must be abstract (true) or concrete (false).
/// </param>
/// <param name="requiredAttributes">
///     Attribute checkers that must all pass. Null or empty means no attribute requirements.
/// </param>
/// <remarks>
///     Validates classes for specifications (static, with attributes) and injectors (partial, accessible).
///     Syntax validation filters by modifiers; symbol validation performs authoritative attribute checks.
///     Returns boolean only; diagnostics are generated by the transformer using this validator.
/// </remarks>
internal sealed class ClassElementValidator(
    CodeElementAccessibility requiredAccessibility = CodeElementAccessibility.Any,
    bool? isStatic = null,
    bool? isAbstract = null,
    IReadOnlyList<IAttributeChecker>? requiredAttributes = null
) : ICodeElementValidator {
    /// <summary>
    ///     Validates public or internal static classes (typical specification class).
    /// </summary>
    public static readonly ClassElementValidator PublicStaticClass = new(
        requiredAccessibility: CodeElementAccessibility.PublicOrInternal,
        isStatic: true);
    
    /// <summary>
    ///     Validates public or internal non-static classes (typical auto-factory target class).
    /// </summary>
    public static readonly ClassElementValidator PublicInstanceClass = new(
        requiredAccessibility: CodeElementAccessibility.PublicOrInternal,
        isStatic: false);

    private readonly IReadOnlyList<IAttributeChecker> requiredAttributes = requiredAttributes ?? ImmutableList<IAttributeChecker>.Empty;

    /// <inheritdoc />
    public bool IsValidSymbol([NotNullWhen(true)] ISymbol? symbol) {
        if (symbol is not ITypeSymbol typeSymbol) {
            return false;
        }
        
        if (requiredAttributes.Any(requiredAttribute => !requiredAttribute.HasAttribute(symbol))) {
            return false;
        }

        if (typeSymbol.TypeKind != TypeKind.Class) {
            return false;
        }

        if (!requiredAccessibility.AccessibilityMatches(typeSymbol.DeclaredAccessibility)) {
            return false;
        }

        if (isStatic != null && isStatic != typeSymbol.IsStatic) {
            return false;
        }

        if (isAbstract != null && isAbstract != typeSymbol.IsAbstract) {
            return false;
        }

        return true;
    }

    /// <inheritdoc />
    /// <remarks>
    ///     <para>Limitation - Attributes Cannot Be Checked:</para>
    ///     <para>
    ///     The syntax-level validation cannot verify attribute types because attributes are just
    ///     syntax nodes here, not resolved symbols. We accept this imprecision - if a class has
    ///     the right modifiers but wrong attributes, it will pass syntax but fail symbol validation.
    ///     The wasted symbol lookup is acceptable given the performance benefit of early filtering.
    ///     </para>
    ///     
    ///     <para>Accessibility Translation:</para>
    ///     <para>
    ///     Syntax modifiers don't map 1:1 to semantic accessibility. For example, a class with no
    ///     modifiers is internally accessible by default. We use heuristics here: if PublicOrInternal
    ///     is required, we reject anything explicitly marked private/protected but accept anything else
    ///     (letting symbol validation make the final determination).
    ///     </para>
    /// </remarks>
    public bool IsValidSyntax(SyntaxNode syntaxNode) {
        if (syntaxNode is not ClassDeclarationSyntax classDeclaration) {
            return false;
        }

        // Note: requiredAttributes check cannot be performed on syntax nodes
        // as attributes are not fully resolved at this stage

        switch (requiredAccessibility) {
            case CodeElementAccessibility.PublicOrInternal:
                // All modifiers must not be private or protected
                if (!classDeclaration.Modifiers
                    .All(modifier => modifier.ValueText switch {
                        "private" or "protected" => false,
                        "internal" or "public" => true,
                        _ => true
                    })) {
                    return false;
                }
                break;
            case CodeElementAccessibility.Any:
                break;
            default:
                // Unknown accessibility, treat as invalid
                return false;
        }

        if (isStatic != null) {
            var hasStaticModifier = classDeclaration.Modifiers.Any(modifier => modifier.ValueText == "static");
            if (isStatic != hasStaticModifier) {
                return false;
            }
        }

        if (isAbstract != null) {
            var hasAbstractModifier = classDeclaration.Modifiers.Any(modifier => modifier.ValueText == "abstract");
            if (isAbstract != hasAbstractModifier) {
                return false;
            }
        }

        return true;
    }
}